title: Sensing the Weather
category: teach
lessons:
    1: Rainfall
    2: Wind Speed
    3: Wind Gust Speed
    4: Wind Direction
    5: Soil Temperature
    6: Ambient Temperature
    7: Relative Humidity
    8: Air Quality
    9: Barometric Pressure
